In [2]:
!nvidia-smi

Thu Jan  2 14:54:15 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8              1W /   35W |     217MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [4]:
import torch

In [5]:
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

In [10]:
T=torch.tensor([1,2,3,4])
print(T, T.device)
t_on_GPU = T.to(device)
t_on_GPU

tensor([1, 2, 3, 4]) cpu


tensor([1, 2, 3, 4], device='cuda:0')

In [11]:
from torch import nn
import matplotlib.pyplot as plt

torch.__version__

'2.5.1+cu124'

In [13]:
w=0.7
b=0.3

X=torch.arange(0, 1, 0.03)
unsqueezed_X=X.unsqueeze(dim=1)
X, unsqueezed_X

(tensor([0.0000, 0.0300, 0.0600, 0.0900, 0.1200, 0.1500, 0.1800, 0.2100, 0.2400,
         0.2700, 0.3000, 0.3300, 0.3600, 0.3900, 0.4200, 0.4500, 0.4800, 0.5100,
         0.5400, 0.5700, 0.6000, 0.6300, 0.6600, 0.6900, 0.7200, 0.7500, 0.7800,
         0.8100, 0.8400, 0.8700, 0.9000, 0.9300, 0.9600, 0.9900]),
 tensor([[0.0000],
         [0.0300],
         [0.0600],
         [0.0900],
         [0.1200],
         [0.1500],
         [0.1800],
         [0.2100],
         [0.2400],
         [0.2700],
         [0.3000],
         [0.3300],
         [0.3600],
         [0.3900],
         [0.4200],
         [0.4500],
         [0.4800],
         [0.5100],
         [0.5400],
         [0.5700],
         [0.6000],
         [0.6300],
         [0.6600],
         [0.6900],
         [0.7200],
         [0.7500],
         [0.7800],
         [0.8100],
         [0.8400],
         [0.8700],
         [0.9000],
         [0.9300],
         [0.9600],
         [0.9900]]))

In [15]:
Y=w*unsqueezed_X+b
Y

tensor([[0.3000],
        [0.3210],
        [0.3420],
        [0.3630],
        [0.3840],
        [0.4050],
        [0.4260],
        [0.4470],
        [0.4680],
        [0.4890],
        [0.5100],
        [0.5310],
        [0.5520],
        [0.5730],
        [0.5940],
        [0.6150],
        [0.6360],
        [0.6570],
        [0.6780],
        [0.6990],
        [0.7200],
        [0.7410],
        [0.7620],
        [0.7830],
        [0.8040],
        [0.8250],
        [0.8460],
        [0.8670],
        [0.8880],
        [0.9090],
        [0.9300],
        [0.9510],
        [0.9720],
        [0.9930]])

In [18]:
unsqueezed_X[:10], Y[:10]

(tensor([[0.0000],
         [0.0300],
         [0.0600],
         [0.0900],
         [0.1200],
         [0.1500],
         [0.1800],
         [0.2100],
         [0.2400],
         [0.2700]]),
 tensor([[0.3000],
         [0.3210],
         [0.3420],
         [0.3630],
         [0.3840],
         [0.4050],
         [0.4260],
         [0.4470],
         [0.4680],
         [0.4890]]))