In [102]:
!nvidia-smi

Sat Dec 28 15:09:25 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   36C    P8              3W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [103]:
import torch
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
print(torch.__version__)


2.5.1+cu124


#TENSORS: multidimensional data(maybe multidimensional matrix), (think of it as a data type)

In [104]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [105]:
scalar.ndim
#gives zero because a scalar has no dimensions, it is a single number

0

In [106]:
#Get the tensor element back as a typecasted into python int
scalar.item()

7

In [107]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [108]:
vector.ndim

1

In [109]:
vector.shape
#returns the number of elements in the vector

torch.Size([2])

In [110]:
#MATRIX
matrix=torch.tensor([[1,2],[2,3]])
matrix

tensor([[1, 2],
        [2, 3]])

In [111]:
matrix.shape
#returns the general shape of the matrix, i.e. mxn

torch.Size([2, 2])

In [112]:
matrix.ndim

2

In [113]:
matrix[0]

tensor([1, 2])

In [114]:
matrix[1]

tensor([2, 3])

In [115]:
matrix[1,1]

tensor(3)

In [116]:
#TENSOR
TENSOR= torch.tensor([[[1,2,3],[4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [117]:
TENSOR.ndim

3

In [118]:
 TENSOR.shape
 #(outer row vector, inner vectors of the outer vector , element in each inner vector )
 #it says 1(the outer most sq bracket), the 3 with middle bracket(for vector each containing 3 elements), then 3 for inner most bracket telling each vector containing 3 elements

torch.Size([1, 3, 3])

In [119]:
print(TENSOR[0], end="\n\n")

print(TENSOR[0,1], end="\n\n")

print(TENSOR[0,1,1])

#here we are giving dimension in the []

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([4, 5, 6])

tensor(5)


Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

neural network: start with random numbers--> look at data--> update random numbers


In [120]:
#createing a random tensor
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4092, 0.1912, 0.5416, 0.9640],
        [0.9019, 0.9101, 0.5462, 0.0151],
        [0.7736, 0.4034, 0.0658, 0.9647]])

In [121]:
random_tensor.ndim

2

In [122]:
random_tensor.shape

torch.Size([3, 4])

In [123]:
#creating a random tensor with similar shape as that of a image tensor
R=torch.rand(size=(200,200,3)) #height, width, color channels
R.shape, R.ndim

(torch.Size([200, 200, 3]), 3)

In [124]:
R[150,150]


tensor([0.2746, 0.8655, 0.4273])

In [125]:
R2=torch.rand(3,4)
z=torch.zeros(3,4)
R2,  z, R2*z

(tensor([[0.2098, 0.9284, 0.7202, 0.2676],
         [0.5032, 0.7943, 0.3288, 0.8662],
         [0.8352, 0.9626, 0.1497, 0.7655]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [126]:
o1=torch.ones(3,4)
o2=torch.ones(3,4)
o1+o2

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [127]:
 z.dtype, o1.dtype

(torch.float32, torch.float32)

In [128]:
o=torch.ones(size=[3,4,5])
o

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [129]:
o[1]=o[1]*0
o
o[1,1,1]=o[1,1,1]+1
o

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

#Creating a range of tensors and tensors-like

In [130]:
k=torch.range(1000,1, -77) #soon "range" is going to get depricated
ott=torch.arange(1, 11, 1)
k, ott

C:\Users\91898\AppData\Local\Temp\ipykernel_13740\3402634198.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  k=torch.range(1000,1, -77) #soon "range" is going to get depricated


(tensor([1000.,  923.,  846.,  769.,  692.,  615.,  538.,  461.,  384.,  307.,
          230.,  153.,   76.]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [131]:
tz=torch.zeros_like(ott)#_like will do make a new tenor like the argument
tz

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor Datatypes

In [132]:
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [133]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #the type of data type the tensor is e.g. float32, float16, etc. for more look at pytorch documentation
                               device="cpu", #what device is your tensor on
                               requires_grad=False)# whether or not to track gradients with this tensor operations
float_32_tensor.dtype



torch.float32

why data type is a big deal while creating a tensor?

**NOTE:** Tensor datatypes has 3 big issues with tensor attributes(errors that we run into) with pytorch and deeplearning
1. Tensors not right datatype(dtype attribute)
2. Tensors not right shape(shape attribute)(shows mostly when we multiply/dot product of 2 tensors)
3. Tensors not on right device(device attribute)(e.g. both the tensors are not on the same device), i.e. cpu, gpu(keyword="cuda"), tpu, etc.), all of the tensors by default will go on cpu unless we state it.

-->They help in precision(the measure of the detail in which the qty is expressed OR the number of digits used to express a value) and computing

NOTE: single-precision floating point is also called float32(i.e the number is represented by 32 bits in the memory same for float16), this make float16 as half-precision.

Though the default is float32

This is used when we are a ok with the sacrifice of detail in which our numbers are being expressed, so that we can calculate faster on the numbers that take less memory.

The below is the solution if we ran into 1st type of dtype problem

In [134]:
F16=float_32_tensor.type(torch.float16) # or we can also do (torch.half)
F16


tensor([3., 6., 9.], dtype=torch.float16)

In [135]:
K=F16*float_32_tensor #this shows that for small operations it does not give datatype issues
K

tensor([ 9., 36., 81.])

In [136]:
I32=torch.tensor([3,4,5], dtype=torch.int16)
F32=torch.tensor([3,4,5], dtype=torch.float32)

In [137]:
k=F32+I32
k, k.dtype

(tensor([ 6.,  8., 10.]), torch.float32)

In [138]:
k.device

device(type='cpu')

In [139]:
k.size(), k.shape #this shows size is a function and shape is an attirbute

(torch.Size([3]), torch.Size([3]))

#Manipulating Tensors(tensor operations)
when we are building neural networks, the NN are comprised of many mathematical functions that our pytorch code is going to run behind the scene for us

Tensor Operatoins include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication(dot product)

In [140]:
TEN=torch.tensor([1,4,7])
TEN+10, torch.add(TEN, 10)

(tensor([11, 14, 17]), tensor([11, 14, 17]))

In [141]:
TEN.dtype

torch.int64

In [142]:
TEN-2, torch.sub(TEN, 2)

(tensor([-1,  2,  5]), tensor([-1,  2,  5]))

In [143]:
TEN*3, torch.mul(TEN, 3)

(tensor([ 3, 12, 21]), tensor([ 3, 12, 21]))

In [144]:
TEN, TEN/2, torch.mul(TEN, 1/2), (TEN/2).dtype #here implicit typecasting takes place

(tensor([1, 4, 7]),
 tensor([0.5000, 2.0000, 3.5000]),
 tensor([0.5000, 2.0000, 3.5000]),
 torch.float32)

In [145]:
TEN, TEN*TEN, torch.mul(TEN, TEN)

(tensor([1, 4, 7]), tensor([ 1, 16, 49]), tensor([ 1, 16, 49]))

In [146]:
%%time
TEN*TEN, TEN@TEN

CPU times: total: 0 ns
Wall time: 0 ns


(tensor([ 1, 16, 49]), tensor(66))

In [147]:
%%time
torch.dot(TEN, TEN)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(66)

In [148]:
%%time
torch.matmul(TEN,TEN)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(66)

In [149]:
T=torch.tensor([[1,2],[3,4],[5,6]])
T, T.shape, T.dtype

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]),
 torch.int64)

In [150]:
A=torch.tensor([[1,2],[3,4],[5,6]])
A, A.shape, A.dtype, A.ndim

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 torch.Size([3, 2]),
 torch.int64,
 2)

In [151]:
AT=torch.transpose(A, 0, 1)
AT, AT.shape, AT.dtype, AT.ndim

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]),
 torch.int64,
 2)

In [152]:
AT@T, T@AT

(tensor([[35, 44],
         [44, 56]]),
 tensor([[ 5, 11, 17],
         [11, 25, 39],
         [17, 39, 61]]))

###Here the contracted dimensions of the two tensors should meet, contracted dimension means

(9, 4, 5)

      |  |

      (4, 5, 7)

In [153]:
C=torch.ones(9,4,5)
C.dtype, C.shape

(torch.float32, torch.Size([9, 4, 5]))

In [154]:
D=torch.ones(4,5,7)
D.dtype, D.shape

(torch.float32, torch.Size([4, 5, 7]))

In [155]:
E=torch.tensordot(C,D)

In [156]:
E, E.shape

(tensor([[20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.],
         [20., 20., 20., 20., 20., 20., 20.]]),
 torch.Size([9, 7]))

##Tensor Aggragation (finding min, max, mean, sum, etc)

In [157]:
x=torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [158]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [159]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [160]:
torch.mean(x.type(torch.float32)), x.type(torch.float16).mean()

(tensor(45.), tensor(45., dtype=torch.float16))

##Finding positional(index value of) min and max

In [161]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, squeezing and unsqueezing tensors

### * Reshaping - reshapes an input tensor to a defined shape


In [162]:
import torch
x = torch.arange(20.,32.)
x, x.shape

(tensor([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31.]),
 torch.Size([12]))

In [163]:
x_reshaped1= x.reshape(3,4)
x_reshaped1, x_reshaped1.shape

(tensor([[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.]]),
 torch.Size([3, 4]))

In [164]:
x_reshaped2= x.reshape(2,3,2)
x_reshaped2, x_reshaped2.shape

(tensor([[[20., 21.],
          [22., 23.],
          [24., 25.]],
 
         [[26., 27.],
          [28., 29.],
          [30., 31.]]]),
 torch.Size([2, 3, 2]))

In [165]:
x_reshaped2= x.reshape(3,2,2)
x_reshaped2, x_reshaped2.shape

(tensor([[[20., 21.],
          [22., 23.]],
 
         [[24., 25.],
          [26., 27.]],
 
         [[28., 29.],
          [30., 31.]]]),
 torch.Size([3, 2, 2]))

In [166]:
x_reshaped3= x.reshape(3,1,2,2)
x_reshaped3, x_reshaped3.shape

(tensor([[[[20., 21.],
           [22., 23.]]],
 
 
         [[[24., 25.],
           [26., 27.]]],
 
 
         [[[28., 29.],
           [30., 31.]]]]),
 torch.Size([3, 1, 2, 2]))

###*View- Return a view of an input tensor of certain shape but keep the same emmory as the original tensor

In [167]:
p=torch.arange(30., 42.)
p, p.shape

(tensor([30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.]),
 torch.Size([12]))

In [168]:
#change the view
p1=p.view(1,12)
p1, p1.shape

(tensor([[30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.]]),
 torch.Size([1, 12]))

In [169]:
p1[:,0] =5
p, p1

#this means that changing p1 will change p because a view of a tensor shares the same memory as the original input tensor.
#i.e. here p1 is the view of p

(tensor([ 5., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.]),
 tensor([[ 5., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.]]))

###* Stacking - combine multiple tensors on top of each other(vstack) or sidebyside

in reallity the same elemnts gets stacked

In [170]:
p_stacked=torch.stack([p,p,p],dim=1) # basically 'dim' is axis(which can take either 0/1 for this example)
p_stacked, p_stacked.shape

(tensor([[ 5.,  5.,  5.],
         [31., 31., 31.],
         [32., 32., 32.],
         [33., 33., 33.],
         [34., 34., 34.],
         [35., 35., 35.],
         [36., 36., 36.],
         [37., 37., 37.],
         [38., 38., 38.],
         [39., 39., 39.],
         [40., 40., 40.],
         [41., 41., 41.]]),
 torch.Size([12, 3]))

###*Squeeze - remove all 1 dimensions from a tensor

In [171]:
r=torch.zeros(2,1,2,1,2)
r, r.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [172]:
r1=torch.squeeze(r)
r1, r1.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [173]:
s=torch.arange(2,14,1)
s, s.size()

(tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]), torch.Size([12]))

In [174]:
s1=s.reshape(1,3,1,4)
s1, s1.size()

(tensor([[[[ 2,  3,  4,  5]],
 
          [[ 6,  7,  8,  9]],
 
          [[10, 11, 12, 13]]]]),
 torch.Size([1, 3, 1, 4]))

In [175]:
s2=torch.squeeze(s1)
s2, s2.size()

(tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]]),
 torch.Size([3, 4]))

### * Unsqueez- add a 1 dimension to a target tensor

In [176]:
s3=torch.unsqueeze(s2, dim=0)
s3=torch.unsqueeze(s3, dim=2)
s3, s3.size()

(tensor([[[[ 2,  3,  4,  5]],
 
          [[ 6,  7,  8,  9]],
 
          [[10, 11, 12, 13]]]]),
 torch.Size([1, 3, 1, 4]))

###* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way OR Rearranges the dimensions of a target tensor in a specified order



In [177]:
u=torch.arange(4,25,1)
u, u.size()

(tensor([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
         22, 23, 24]),
 torch.Size([21]))

In [178]:
u1=u.reshape(3,1,7)
u1, u1.size()

(tensor([[[ 4,  5,  6,  7,  8,  9, 10]],
 
         [[11, 12, 13, 14, 15, 16, 17]],
 
         [[18, 19, 20, 21, 22, 23, 24]]]),
 torch.Size([3, 1, 7]))

In [179]:
u2=torch.permute(u1, (2,0,1)) #the bracket values are the dimension values(i.e we are swapping the dimensions within the tensor)
u2, u2.size()

(tensor([[[ 4],
          [11],
          [18]],
 
         [[ 5],
          [12],
          [19]],
 
         [[ 6],
          [13],
          [20]],
 
         [[ 7],
          [14],
          [21]],
 
         [[ 8],
          [15],
          [22]],
 
         [[ 9],
          [16],
          [23]],
 
         [[10],
          [17],
          [24]]]),
 torch.Size([7, 3, 1]))

In [180]:
#we usually apply permute on images
v=torch.rand(size=(224, 224,3), dtype=torch.float32) #here (height, width, color_channels
v, v.size()

(tensor([[[0.6667, 0.7343, 0.0269],
          [0.0212, 0.4932, 0.2510],
          [0.0633, 0.1027, 0.6681],
          ...,
          [0.6105, 0.5679, 0.5515],
          [0.5515, 0.1393, 0.2148],
          [0.9872, 0.7008, 0.3035]],
 
         [[0.6662, 0.5694, 0.1247],
          [0.9667, 0.0462, 0.3192],
          [0.9914, 0.9953, 0.6776],
          ...,
          [0.1243, 0.8436, 0.9420],
          [0.8903, 0.0321, 0.5744],
          [0.2833, 0.5610, 0.0594]],
 
         [[0.0600, 0.2181, 0.9233],
          [0.8314, 0.1347, 0.7113],
          [0.4737, 0.7764, 0.5249],
          ...,
          [0.1910, 0.8847, 0.9253],
          [0.0778, 0.9220, 0.7950],
          [0.5255, 0.3295, 0.5828]],
 
         ...,
 
         [[0.8877, 0.5367, 0.6399],
          [0.3294, 0.1963, 0.9483],
          [0.2470, 0.8325, 0.5273],
          ...,
          [0.2795, 0.8615, 0.7017],
          [0.2638, 0.4948, 0.0876],
          [0.2134, 0.8163, 0.8794]],
 
         [[0.1934, 0.8504, 0.3112],
          [0

In [181]:
v1=torch.squeeze(v) #this will have no effect because no 1-dimension in the tensor
v1, v1.size()

(tensor([[[0.6667, 0.7343, 0.0269],
          [0.0212, 0.4932, 0.2510],
          [0.0633, 0.1027, 0.6681],
          ...,
          [0.6105, 0.5679, 0.5515],
          [0.5515, 0.1393, 0.2148],
          [0.9872, 0.7008, 0.3035]],
 
         [[0.6662, 0.5694, 0.1247],
          [0.9667, 0.0462, 0.3192],
          [0.9914, 0.9953, 0.6776],
          ...,
          [0.1243, 0.8436, 0.9420],
          [0.8903, 0.0321, 0.5744],
          [0.2833, 0.5610, 0.0594]],
 
         [[0.0600, 0.2181, 0.9233],
          [0.8314, 0.1347, 0.7113],
          [0.4737, 0.7764, 0.5249],
          ...,
          [0.1910, 0.8847, 0.9253],
          [0.0778, 0.9220, 0.7950],
          [0.5255, 0.3295, 0.5828]],
 
         ...,
 
         [[0.8877, 0.5367, 0.6399],
          [0.3294, 0.1963, 0.9483],
          [0.2470, 0.8325, 0.5273],
          ...,
          [0.2795, 0.8615, 0.7017],
          [0.2638, 0.4948, 0.0876],
          [0.2134, 0.8163, 0.8794]],
 
         [[0.1934, 0.8504, 0.3112],
          [0

In [182]:
v2=torch.permute(v,(2,0,1)) #here (color_channels, height, width)
v2, v2.shape

(tensor([[[0.6667, 0.0212, 0.0633,  ..., 0.6105, 0.5515, 0.9872],
          [0.6662, 0.9667, 0.9914,  ..., 0.1243, 0.8903, 0.2833],
          [0.0600, 0.8314, 0.4737,  ..., 0.1910, 0.0778, 0.5255],
          ...,
          [0.8877, 0.3294, 0.2470,  ..., 0.2795, 0.2638, 0.2134],
          [0.1934, 0.0127, 0.8455,  ..., 0.4119, 0.4558, 0.2869],
          [0.3531, 0.6187, 0.9975,  ..., 0.4556, 0.6020, 0.0487]],
 
         [[0.7343, 0.4932, 0.1027,  ..., 0.5679, 0.1393, 0.7008],
          [0.5694, 0.0462, 0.9953,  ..., 0.8436, 0.0321, 0.5610],
          [0.2181, 0.1347, 0.7764,  ..., 0.8847, 0.9220, 0.3295],
          ...,
          [0.5367, 0.1963, 0.8325,  ..., 0.8615, 0.4948, 0.8163],
          [0.8504, 0.7996, 0.2051,  ..., 0.6746, 0.2482, 0.8564],
          [0.2036, 0.9383, 0.5550,  ..., 0.9597, 0.8223, 0.5276]],
 
         [[0.0269, 0.2510, 0.6681,  ..., 0.5515, 0.2148, 0.3035],
          [0.1247, 0.3192, 0.6776,  ..., 0.9420, 0.5744, 0.0594],
          [0.9233, 0.7113, 0.5249,  ...,

In [183]:
v4 = (torch.rand(256, 256, 3) * 255).to(torch.uint8)
v4, v4.shape


(tensor([[[146,   4,   3],
          [210,  95,  99],
          [232,  82, 216],
          ...,
          [110, 214, 118],
          [ 10, 210, 175],
          [ 40, 224,  73]],
 
         [[ 16, 145,  59],
          [ 36,  54, 135],
          [243,  45, 204],
          ...,
          [181,  35, 133],
          [ 10, 155,  17],
          [184, 158, 217]],
 
         [[  8, 176,  36],
          [113,   7,  27],
          [247,  43,  78],
          ...,
          [247,  38, 205],
          [130,  62, 233],
          [  3, 150, 228]],
 
         ...,
 
         [[ 18,  12, 205],
          [204,  60, 254],
          [220, 180,  22],
          ...,
          [124,  21,  77],
          [237, 218, 210],
          [ 21,  16, 160]],
 
         [[ 54, 171, 127],
          [ 82,  95,  33],
          [202,  97, 123],
          ...,
          [218, 215, 137],
          [189,  50,  11],
          [ 62, 194, 164]],
 
         [[122, 233, 125],
          [105, 182,  77],
          [ 48,  27, 188],
   

#Indexing in pytorch is same as Indexing in numpy

In [184]:
w = torch.arange(1,10).reshape(1,3,3)
w,w.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [185]:
w[0][0][1]=24
w

tensor([[[ 1, 24,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]]])

In [186]:
w[:,:,2], w[0,1,2], w[0][1][2]

(tensor([[3, 6, 9]]), tensor(6), tensor(6))

##Pytorch tensors & Numpy

Pytorch has functionality to interact with numpy

* Data in numpy, want in pytorch tensor-> `torch.from_numpy(ndarray_name)`

* Data in pytorch tensor, want in numpy array-> `torch.Tensor.numpy()`

In [187]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

###Note: By default, NumPy arrays are created with the default datatype of float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (i.e float64).

###However, many PyTorch calculations outputs arr by default in float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

Because we reassigned tensor above, if you change the tensor, the array stays the same.


[ ]


In [188]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

###And if you want to go from PyTorch tensor to NumPy array, you can call `tensor.numpy()`.


In [189]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [190]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#GPU acces

In [191]:
!nvidia-smi

Sat Dec 28 15:09:29 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   37C    P8              3W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [192]:
import torch
torch.cuda.is_available()

True